// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ios-home",
    platforms: [
        .iOS("16.0"),
        .macOS("13.0")
    ],
    products: [
        .iOSApplication(
            name: "ios-home",
            targets: ["ios-home"],
            bundleIdentifier: "com.check24.ios-home",
            teamIdentifier: "RP5ATKHYZT",
            displayVersion: "1.0",
            bundleVersion: "1",
            supportedDeviceFamilies: [
                .phone,
                .pad
            ],
            supportedInterfaceOrientations: [
                .portrait
            ],
            capabilities: [
                .outgoingNetworkConnections()
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "ios-home",
            path: ".",
            exclude: ["Tests", "Config", "Logging", "Package.swift.backup"],
            sources: ["HomeApp.swift", "Views", "Components", "Models", "Networking", "ViewModels"]
        )
    ]
)